export const browserCoreExamples = [
  "alphaclaw browser status",
  "alphaclaw browser start",
  "alphaclaw browser stop",
  "alphaclaw browser tabs",
  "alphaclaw browser open https://example.com",
  "alphaclaw browser focus abcd1234",
  "alphaclaw browser close abcd1234",
  "alphaclaw browser screenshot",
  "alphaclaw browser screenshot --full-page",
  "alphaclaw browser screenshot --ref 12",
  "alphaclaw browser snapshot",
  "alphaclaw browser snapshot --format aria --limit 200",
  "alphaclaw browser snapshot --efficient",
  "alphaclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "alphaclaw browser navigate https://example.com",
  "alphaclaw browser resize 1280 720",
  "alphaclaw browser click 12 --double",
  'alphaclaw browser type 23 "hello" --submit',
  "alphaclaw browser press Enter",
  "alphaclaw browser hover 44",
  "alphaclaw browser drag 10 11",
  "alphaclaw browser select 9 OptionA OptionB",
  "alphaclaw browser upload /tmp/file.pdf",
  'alphaclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "alphaclaw browser dialog --accept",
  'alphaclaw browser wait --text "Done"',
  "alphaclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "alphaclaw browser console --level error",
  "alphaclaw browser pdf",
];
