#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${ALPHACLAW_INSTALL_E2E_IMAGE:-${ALPHACLAW_INSTALL_E2E_IMAGE:-alphaclaw-install-e2e:local}}"
INSTALL_URL="${ALPHACLAW_INSTALL_URL:-${ALPHACLAW_INSTALL_URL:-https://alphaclaw.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
ALPHACLAW_E2E_MODELS="${ALPHACLAW_E2E_MODELS:-${ALPHACLAW_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e ALPHACLAW_INSTALL_URL="$INSTALL_URL" \
  -e ALPHACLAW_INSTALL_TAG="${ALPHACLAW_INSTALL_TAG:-${ALPHACLAW_INSTALL_TAG:-latest}}" \
  -e ALPHACLAW_E2E_MODELS="$ALPHACLAW_E2E_MODELS" \
  -e ALPHACLAW_INSTALL_E2E_PREVIOUS="${ALPHACLAW_INSTALL_E2E_PREVIOUS:-${ALPHACLAW_INSTALL_E2E_PREVIOUS:-}}" \
  -e ALPHACLAW_INSTALL_E2E_SKIP_PREVIOUS="${ALPHACLAW_INSTALL_E2E_SKIP_PREVIOUS:-${ALPHACLAW_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
