/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SkillsRouteImport } from "./routes/skills"
import { Route as SessionsRouteImport } from "./routes/sessions"
import { Route as OverviewRouteImport } from "./routes/overview"
import { Route as NodesRouteImport } from "./routes/nodes"
import { Route as LogsRouteImport } from "./routes/logs"
import { Route as InstancesRouteImport } from "./routes/instances"
import { Route as DebugRouteImport } from "./routes/debug"
import { Route as CronRouteImport } from "./routes/cron"
import { Route as ConfigRouteImport } from "./routes/config"
import { Route as ChatRouteImport } from "./routes/chat"
import { Route as ChannelsRouteImport } from "./routes/channels"
import { Route as AgentsRouteImport } from "./routes/agents"
import { Route as IndexRouteImport } from "./routes/index"

const SkillsRoute = SkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: "/nodes",
  path: "/nodes",
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: "/instances",
  path: "/instances",
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: "/debug",
  path: "/debug",
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: "/cron",
  path: "/cron",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/agents": typeof AgentsRoute
  "/channels": typeof ChannelsRoute
  "/chat": typeof ChatRoute
  "/config": typeof ConfigRoute
  "/cron": typeof CronRoute
  "/debug": typeof DebugRoute
  "/instances": typeof InstancesRoute
  "/logs": typeof LogsRoute
  "/nodes": typeof NodesRoute
  "/overview": typeof OverviewRoute
  "/sessions": typeof SessionsRoute
  "/skills": typeof SkillsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/agents": typeof AgentsRoute
  "/channels": typeof ChannelsRoute
  "/chat": typeof ChatRoute
  "/config": typeof ConfigRoute
  "/cron": typeof CronRoute
  "/debug": typeof DebugRoute
  "/instances": typeof InstancesRoute
  "/logs": typeof LogsRoute
  "/nodes": typeof NodesRoute
  "/overview": typeof OverviewRoute
  "/sessions": typeof SessionsRoute
  "/skills": typeof SkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/agents": typeof AgentsRoute
  "/channels": typeof ChannelsRoute
  "/chat": typeof ChatRoute
  "/config": typeof ConfigRoute
  "/cron": typeof CronRoute
  "/debug": typeof DebugRoute
  "/instances": typeof InstancesRoute
  "/logs": typeof LogsRoute
  "/nodes": typeof NodesRoute
  "/overview": typeof OverviewRoute
  "/sessions": typeof SessionsRoute
  "/skills": typeof SkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/agents"
    | "/channels"
    | "/chat"
    | "/config"
    | "/cron"
    | "/debug"
    | "/instances"
    | "/logs"
    | "/nodes"
    | "/overview"
    | "/sessions"
    | "/skills"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/agents"
    | "/channels"
    | "/chat"
    | "/config"
    | "/cron"
    | "/debug"
    | "/instances"
    | "/logs"
    | "/nodes"
    | "/overview"
    | "/sessions"
    | "/skills"
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/channels"
    | "/chat"
    | "/config"
    | "/cron"
    | "/debug"
    | "/instances"
    | "/logs"
    | "/nodes"
    | "/overview"
    | "/sessions"
    | "/skills"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChannelsRoute: typeof ChannelsRoute
  ChatRoute: typeof ChatRoute
  ConfigRoute: typeof ConfigRoute
  CronRoute: typeof CronRoute
  DebugRoute: typeof DebugRoute
  InstancesRoute: typeof InstancesRoute
  LogsRoute: typeof LogsRoute
  NodesRoute: typeof NodesRoute
  OverviewRoute: typeof OverviewRoute
  SessionsRoute: typeof SessionsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/skills": {
      id: "/skills"
      path: "/skills"
      fullPath: "/skills"
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sessions": {
      id: "/sessions"
      path: "/sessions"
      fullPath: "/sessions"
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/overview": {
      id: "/overview"
      path: "/overview"
      fullPath: "/overview"
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/nodes": {
      id: "/nodes"
      path: "/nodes"
      fullPath: "/nodes"
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/logs": {
      id: "/logs"
      path: "/logs"
      fullPath: "/logs"
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/instances": {
      id: "/instances"
      path: "/instances"
      fullPath: "/instances"
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/debug": {
      id: "/debug"
      path: "/debug"
      fullPath: "/debug"
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cron": {
      id: "/cron"
      path: "/cron"
      fullPath: "/cron"
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/config": {
      id: "/config"
      path: "/config"
      fullPath: "/config"
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/chat": {
      id: "/chat"
      path: "/chat"
      fullPath: "/chat"
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/channels": {
      id: "/channels"
      path: "/channels"
      fullPath: "/channels"
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/agents": {
      id: "/agents"
      path: "/agents"
      fullPath: "/agents"
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChannelsRoute: ChannelsRoute,
  ChatRoute: ChatRoute,
  ConfigRoute: ConfigRoute,
  CronRoute: CronRoute,
  DebugRoute: DebugRoute,
  InstancesRoute: InstancesRoute,
  LogsRoute: LogsRoute,
  NodesRoute: NodesRoute,
  OverviewRoute: OverviewRoute,
  SessionsRoute: SessionsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
